alter session set "_ORACLE_SCRIPT"=true; 
/
--CS#6
--TAO ROLE TDA
DROP ROLE ROLE_TRUONGDEAN;
CREATE ROLE ROLE_TRUONGDEAN;

--CAP QUYEN CHO ROLE_TRUONGDEAN
GRANT INSERT, DELETE, UPDATE ON DEAN TO ROLE_TRUONGDEAN;
/
-- Cấp role cho tất cả TRƯỞNG ĐỀ ÁN
CREATE OR REPLACE PROCEDURE USP_GRANT_ROLE_TRUONGDEAN
AS
    CURSOR CUR IS SELECT MANV FROM NHANVIEN$ WHERE UPPER(MANV) IN (SELECT USERNAME FROM ALL_USERS) AND VAITRO = N'Trưởng đề án';
    strSQL varchar(2000);
    usr varchar(60);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'GRANT ROLE_TRUONGDEAN TO ' || usr;
        EXECUTE IMMEDIATE (strSQL);
        
    END LOOP;
END;
/
EXEC USP_GRANT_ROLE_TRUONGDEAN


SELECT * FROM U_AD_QLNV.PHANCONG