-- Tạo một bảng tạm có tên là NHANVIEN_ENCRYPTED với kiểu dữ liệu của LUONG và PHUCAP là VARCHAR2(32 BYTE).

CREATE TABLE U_AD_QLNV.NHANVIEN_ENCRYPTED 
(	MANV VARCHAR2(50 BYTE), 
    TENNV NVARCHAR2(50), 
    PHAI NVARCHAR2(3), 
    NGAYSINH DATE, 
    DIACHI NVARCHAR2(255), 
    SODT VARCHAR2(15 BYTE), 
    LUONG VARCHAR2(32 BYTE), 
    PHUCAP VARCHAR2(32 BYTE), 
    VAITRO NVARCHAR2(20), 
    MANQL VARCHAR2(50 BYTE), 
    PHG VARCHAR2(50 BYTE)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE USERS;

SELECT * FROM U_AD_QLNV.NHANVIEN_ENCRYPTED 