-- Connect with user U_AD

DROP TABLE HSBA_DV purge;
DROP TABLE HSBA purge;
DROP TABLE NHANVIEN purge;
DROP TABLE BENHNHAN purge;
DROP TABLE KHOA purge;
DROP TABLE CSYT purge;

CREATE TABLE CSYT
(
    MACSYT NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    TENCSYT NVARCHAR2(50) NOT NULL,
    DCCSYT NVARCHAR2(255) NOT NULL,
    SDTCSYT VARCHAR(15) NOT NULL,
    USERNAME VARCHAR(50)
);

--TAO BANG BENH NHAN
CREATE TABLE BENHNHAN
(
    MABN NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    MACSYT NUMBER ,
    TENBN NVARCHAR2(50) ,
    CMND VARCHAR2(255) ,
    NGAYSINH DATE ,
    SONHA NVARCHAR2(50),
    TENDUONG NVARCHAR2(50) ,
    QUANHUYEN NVARCHAR2(50) ,
    TINHTP NVARCHAR2(50) ,
    TIENSUBENH NVARCHAR2(255),
    TIENSUBENHGD NVARCHAR2(255),
    DIUNGTHUOC NVARCHAR2(255),
    USERNAME VARCHAR(50),
    
    FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT)
);

--TAO BANG NHAN VIEN
CREATE TABLE NHANVIEN
(
    MANV NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    HOTEN NVARCHAR2(50) ,
    PHAI NVARCHAR2(3) ,
    NGAYSINH DATE ,
    CMND VARCHAR2(255) ,
    QUEQUAN NVARCHAR2(50) ,
    SODT VARCHAR(15) ,
    CSYT NUMBER ,
    VAITRO NVARCHAR2(20) CHECK (VAITRO IN (N'Thanh tra',N'Y si',N'Bac si',N'Nghien cuu',N'Co so y te')),
    CHUYENKHOA NVARCHAR2(255),
    USERNAME VARCHAR(50),
    
    FOREIGN KEY (CSYT) REFERENCES CSYT(MACSYT)
);

--TAO BANG CHUYENKHOA
CREATE TABLE KHOA
(
    MAKHOA NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    TENKHOA NVARCHAR2(255)
);

--TAO BANG HSBA
CREATE TABLE HSBA
(
    MAHSBA NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT by 1) PRIMARY KEY,
    MABN NUMBER NOT NULL,
    NGAY DATE NOT NULL,
    CHANDOAN NVARCHAR2(255) NOT NULL,
    MABS NUMBER NOT NULL,
    MAKHOA NUMBER NOT NULL,
    MACSYT NUMBER NOT NULL,
    KETLUAN NVARCHAR2(255) NOT NULL,
    
    FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MACSYT) REFERENCES CSYT(MACSYT),
    FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

--TAO BANG HSBA_DV
CREATE TABLE HSBA_DV
(
   MA_HSBA NUMBER,
   MADV NUMBER,
   NGAY DATE,
   MAKTV NUMBER NOT NULL,
   KETQUA NVARCHAR2(255),
   
   PRIMARY KEY(MA_HSBA,MADV,NGAY),
   FOREIGN KEY (MA_HSBA) REFERENCES HSBA(MAHSBA),
   FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV)
);


--TABLE CSYT
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT,USERNAME) VALUES (N'Ha Noi', N'17 Dong Da', '0123456789','CSYT1');
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT,USERNAME) VALUES (N'Da Nang', N'20 Tran Phu', '0147852369','CSYT2');
INSERT INTO CSYT(TENCSYT, DCCSYT, SDTCSYT,USERNAME) VALUES (N'Ho Chi Minh', N'123 Nguyen Van Cu', '0123789456','CSYT3');

--TABLE BENHNHAN
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (1,N'Nguyen Van Anh', '123456', TO_DATE('2002/12/03 ', 'yyyy/mm/dd '), N'21/2c', N'Tran Phu', N'Tp. Da Lat', N'Lam Dong', N'Ho', N'Khong co', N'Khong co');
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (2,N'Le Van Bay', '1234567', TO_DATE('2002/2/16 ', 'yyyy/mm/dd '), N'23/4b', N'Ly Thai To', N'Tp. Ho Chi Minh', N'Lao Cai', N'Viem xoang', N'Khong co', N'Khong co');
INSERT INTO BENHNHAN(MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) VALUES (3,N'Tran Huu Trong', '1234568', TO_DATE('2002/5/16 ', 'yyyy/mm/dd '), N'10/3e', N'Hai Ba Trung', N'Tp. Da Nang', N'Da Nang', N'Khong co', N'Khong co', N'Khong co');

--TABLE NHANVIEN
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Vo Hoang Quan',N'Nam', TO_DATE('1997/3/27 ', 'yyyy/mm/dd'),'12345',N'Tp. Da Lat','0852576182',1,N'Thanh tra',N'', 'THANHTRA_1');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Le Van Luu',N'Nam', TO_DATE('1997/7/23 ', 'yyyy/mm/dd'),'12354',N'Tp. Ho Chinh Minh','0852576212',1,N'Co so y te',N'', 'CSYT_1');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Thi Hong',N'Nu', TO_DATE('1965/3/22 ', 'yyyy/mm/dd'),'12351',N'Tp. Ho Chinh Minh','0852345282',1,N'Bac si',N'Da khoa', 'YBACSI_1');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Tran Van Sy',N'Nam', TO_DATE('1999/4/27 ', 'yyyy/mm/dd'),'12361',N'Tp. Ho Chinh Minh','0852545281',1,N'Nghien cuu',N'Da khoa', 'NGHIENCUU_1');

INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Tran Hong Nhung',N'Nu', TO_DATE('1991/3/24 ', 'yyyy/mm/dd'),'21234',N'Tp. Da Lat','0852516182',1,N'Thanh tra',N'', 'THANHTRA_2');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Le Van Ly',N'Nam', TO_DATE('1998/8/23 ', 'yyyy/mm/dd'),'21233',N'Tp. Ho Chinh Minh','0852516212',1,N'Co so y te',N'', 'CSYT_2');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Thi Ha',N'Nu', TO_DATE('1966/1/22 ', 'yyyy/mm/dd'),'21235',N'Tp. Da Lat','0852315282',1,N'Bac si',N'Rang ham mat', 'YBACSI_2');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Tran Thanh Long',N'Nam', TO_DATE('1992/5/27 ', 'yyyy/mm/dd'),'21236',N'Tp. Ho Chinh Minh','0852515281',1,N'Nghien cuu',N'Da khoa', 'NGHIENCUU_2');


INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Le Tran Huy',N'Nam', TO_DATE('1989/5/08 ', 'yyyy/mm/dd'),'32345',N'Tp. Da Nang','0812576182',1,N'Thanh tra',N'', 'THANHTRA_3');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Van Truong',N'Nam', TO_DATE('1991/3/11 ', 'yyyy/mm/dd'),'32354',N'Tp. Da Lat','0812576212',1,N'Co so y te',N'', 'CSYT_3');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Thi Huong',N'Nu', TO_DATE('1969/1/12 ', 'yyyy/mm/dd'),'32351',N'Tp. Ho Chinh Minh','0812345282',1,N'Bac si',N'Tai mui hong', 'YBACSI_3');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Tran Sy Dien',N'Nam', TO_DATE('1989/9/07 ', 'yyyy/mm/dd'),'32361',N'Tp. Da Lat','0812545281',1,N'Nghien cuu',N'Da khoa', 'NGHIENCUU_3');

INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Kim',N'Nu', TO_DATE('1991/1/23 ', 'yyyy/mm/dd'),'1235',N'Tp. Da Lat','0852345282',1,N'Thanh tra',N'Da khoa','THANHTRA_6');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA, USERNAME) VALUES(N'Nguyen Khuyen',N'Nu', TO_DATE('1989/8/22 ', 'yyyy/mm/dd'),'1236',N'Tp. Da Nang','0851545282',1,N'Thanh tra',N'Da khoa','THANHTRA_7');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA,USERNAME) VALUES(N'Nguyen Vu Truong',N'Nam', TO_DATE('1990/2/10 ', 'yyyy/mm/dd'),'1235',N'Tp. Da Lat','0812345282',1,N'Thanh tra',N'Da khoa','THANHTRA_8');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA,USERNAME) VALUES(N'Nguyen Khuyen Ha',N'Nu', TO_DATE('1997/4/17 ', 'yyyy/mm/dd'),'1236',N'Tp. Ho Chi Minh','0852645282',1,N'Thanh tra',N'Da khoa','THANHTRA_9');
INSERT INTO NHANVIEN(HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, CSYT, VAITRO, CHUYENKHOA,USERNAME) VALUES(N'Nguyen Kim Tuyen',N'Nu', TO_DATE('1995/3/27 ', 'yyyy/mm/dd'),'1235',N'Tp. Da Lat','0852345382',1,N'Thanh tra',N'Da khoa','THANHTRA_10');

--TABLE KHOA
INSERT INTO KHOA(TENKHOA) VALUES(N'Da khoa');
INSERT INTO KHOA(TENKHOA) VALUES(N'Rang ham mat');
INSERT INTO KHOA(TENKHOA) VALUES(N'Tai mui hong');

--TABLE HSBA
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(1, TO_DATE('2023/3/20 ', 'yyyy/mm/dd'), N'Viem xoang',3,1,1,N'Viem xoang');
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(2, TO_DATE('2023/2/23 ', 'yyyy/mm/dd'), N'Cam cum',7,1,2,N'Cam cum');
INSERT INTO HSBA(MABN, NGAY, CHANDOAN, MABS, MAKHOA, MACSYT, KETLUAN) VALUES(3, TO_DATE('2023/1/26 ', 'yyyy/mm/dd'), N'COVID',11,1,3,N'COVID');

--TABLE HSBA_DV
INSERT INTO HSBA_DV(MA_HSBA, MADV, NGAY, MAKTV, KETQUA) VALUES(1,1, TO_DATE('2023/3/20 ', 'yyyy/mm/dd'), 2, N'OK');
INSERT INTO HSBA_DV(MA_HSBA, MADV, NGAY, MAKTV, KETQUA) VALUES(2,2, TO_DATE('2023/2/23 ', 'yyyy/mm/dd'), 6, N'FAIL');
INSERT INTO HSBA_DV(MA_HSBA, MADV, NGAY, MAKTV, KETQUA) VALUES(3,3, TO_DATE('2023/1/26 ', 'yyyy/mm/dd'), 10, N'OK');

select * from NHANVIEN